// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adefc19e7e2b7202 "S Clark - ArcAlert", do not edit manually */
"use client";

// virtual:contact-icon
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Exu4beRoFwFpg1rJBI70/ArTBrP4jMtR0IZrV5uDT/xFjtBMzU9.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, RichText, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-S5wXt";
var variantClassNames = { VE7jRg8wN: "framer-v-1vrm4bs" };
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var getProps = ({ contactName, height, id, width, ...props }) => {
  return { ...props, PgDSGOHNR: contactName ?? props.PgDSGOHNR ?? "Jon" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, PgDSGOHNR, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "VE7jRg8wN", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-1vrm4bs", className, classNames), "data-framer-name": "Variant 1", layoutDependency, layoutId: "VE7jRg8wN", ref: ref ?? ref1, style: { backgroundColor: "var(--token-8a3dc925-cf3f-4305-931b-abd8bce0f792, rgb(255, 252, 252))", borderBottomLeftRadius: 100, borderBottomRightRadius: 100, borderTopLeftRadius: 100, borderTopRightRadius: 100, ...style }, children: /* @__PURE__ */ _jsx(RichText, { __fromCanvasComponent: true, children: /* @__PURE__ */ _jsx(React.Fragment, { children: /* @__PURE__ */ _jsx(motion.p, { style: { "--font-selector": "SW1wYWN0", "--framer-font-family": '"Impact", sans-serif', "--framer-text-alignment": "center", "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c1c270e0-de6e-4b8d-aa53-133f44069f0a, rgb(54, 52, 52)))" }, children: "Jon" }) }), className: "framer-1gj6vy2", fonts: ["Impact"], layoutDependency, layoutId: "NDt8b5kyl", style: { "--extracted-r6o4lv": "var(--token-c1c270e0-de6e-4b8d-aa53-133f44069f0a, rgb(54, 52, 52))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline" }, text: PgDSGOHNR, transformTemplate: transformTemplate1, verticalAlignment: "top", withExternalLayout: true }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-S5wXt.framer-11offuc, .framer-S5wXt .framer-11offuc { display: block; }", ".framer-S5wXt.framer-1vrm4bs { height: 60px; overflow: visible; position: relative; width: 60px; }", ".framer-S5wXt .framer-1gj6vy2 { flex: none; height: auto; left: 50%; position: absolute; top: 48%; white-space: pre; width: auto; }"];
var FramerxFjtBMzU9 = withCSS(Component, css, "framer-S5wXt");
var stdin_default = FramerxFjtBMzU9;
FramerxFjtBMzU9.displayName = "ContactIcon";
FramerxFjtBMzU9.defaultProps = { height: 60, width: 60 };
addPropertyControls(FramerxFjtBMzU9, { PgDSGOHNR: { defaultValue: "Jon", displayTextArea: false, title: "ContactName", type: ControlType.String } });
addFonts(FramerxFjtBMzU9, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:contact-icon
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "augiA20Il": { "path": "/" }, "iraOLFFrB": { "path": "/page" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "adefc19e7e2b72020fbf521cecd912ab5637e568e46b1420e141bd14e0cd2ee5",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "augiA20Il": {
          "path": "/"
        },
        "iraOLFFrB": {
          "path": "/page"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "adefc19e7e2b72020fbf521cecd912ab5637e568e46b1420e141bd14e0cd2ee5",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
