// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adefc19e7e2b7202 "S Clark - ArcAlert", do not edit manually */
"use client";

// virtual:header-image
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7GKnsgdE8F1S91HJkwas/jipLywAFZwWkUhVzg7nv/fnKmpk5M2.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, getLoadingLazyAtYPosition, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-R7w1D";
var variantClassNames = { XbxxW6rws: "framer-v-dr1bxr" };
var toResponsiveImage = (value) => {
  if (typeof value === "object" && value !== null && typeof value.src === "string") {
    return value;
  }
  return typeof value === "string" ? { src: value } : void 0;
};
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, width, ...props }) => {
  return { ...props, ilJUTjLWL: image ?? props.ilJUTjLWL ?? { alt: "", src: "https://framerusercontent.com/images/bGVkd3wzuuQyvQmPJlwTd44HE.png?scale-down-to=1024", srcSet: "https://framerusercontent.com/images/bGVkd3wzuuQyvQmPJlwTd44HE.png?scale-down-to=512 512w,https://framerusercontent.com/images/bGVkd3wzuuQyvQmPJlwTd44HE.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/bGVkd3wzuuQyvQmPJlwTd44HE.png 1200w" } };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ilJUTjLWL, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "XbxxW6rws", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(Image, { ...restProps, ...gestureHandlers, background: { alt: "", loading: getLoadingLazyAtYPosition(componentViewport?.y || 0), sizes: componentViewport?.width || "100vw", ...toResponsiveImage(ilJUTjLWL), ...{ positionX: "center", positionY: "center" } }, className: cx(scopingClassNames, "framer-dr1bxr", className, classNames), "data-framer-name": "Variant 1", layoutDependency, layoutId: "XbxxW6rws", ref: ref ?? ref1, style: { ...style } }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-R7w1D.framer-7siwq7, .framer-R7w1D .framer-7siwq7 { display: block; }", ".framer-R7w1D.framer-dr1bxr { height: 389px; overflow: hidden; position: relative; width: 558px; }"];
var FramerfnKmpk5M2 = withCSS(Component, css, "framer-R7w1D");
var stdin_default = FramerfnKmpk5M2;
FramerfnKmpk5M2.displayName = "HeaderImage";
FramerfnKmpk5M2.defaultProps = { height: 389, width: 558 };
addPropertyControls(FramerfnKmpk5M2, { ilJUTjLWL: { __defaultAssetReference: "data:framer/asset-reference,bGVkd3wzuuQyvQmPJlwTd44HE.png?originalFilename=image.png&preferredSize=auto", __vekterDefault: { alt: "", assetReference: "data:framer/asset-reference,bGVkd3wzuuQyvQmPJlwTd44HE.png?originalFilename=image.png&preferredSize=auto" }, title: "Image", type: ControlType.ResponsiveImage } });
addFonts(FramerfnKmpk5M2, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:header-image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "augiA20Il": { "path": "/" }, "iraOLFFrB": { "path": "/page" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "adefc19e7e2b72020fbf521cecd912ab5637e568e46b1420e141bd14e0cd2ee5",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "augiA20Il": {
          "path": "/"
        },
        "iraOLFFrB": {
          "path": "/page"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "adefc19e7e2b72020fbf521cecd912ab5637e568e46b1420e141bd14e0cd2ee5",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
