// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adefc19e7e2b7202 "S Clark - ArcAlert", do not edit manually */
"use client";

// virtual:modern-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tHRczyOfNqOSPVo3H6wQ/K617MfjvHZFsqw3yWZLO/PyNg7eZF4.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, RichText, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["dioJdgZpP", "EVeBZmw_N"];
var serializationHash = "framer-mWeqH";
var variantClassNames = { dioJdgZpP: "framer-v-fm9ith", EVeBZmw_N: "framer-v-1aeiqaq" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { "Variant 1": "dioJdgZpP", "Variant 2": "EVeBZmw_N" };
var getProps = ({ background, color, height, id, onClick, text, width, ...props }) => {
  return { ...props, IsETT2OVl: background ?? props.IsETT2OVl ?? "rgb(255, 90, 87)", reO7G_gfv: text ?? props.reO7G_gfv ?? "ButtonText", RN58auS3W: onClick ?? props.RN58auS3W, SrMRtag9J: color ?? props.SrMRtag9J ?? "var(--token-805b626f-2081-48a3-9772-b35985201e4d, rgb(255, 250, 250))", variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "dioJdgZpP" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, IsETT2OVl, SrMRtag9J, RN58auS3W, reO7G_gfv, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "dioJdgZpP", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
  const onTapz3vecs = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (RN58auS3W) {
      const res = await RN58auS3W(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-fm9ith", className, classNames), "data-framer-name": "Variant 1", "data-highlight": true, layoutDependency, layoutId: "dioJdgZpP", onTap: onTapz3vecs, ref: refBinding, style: { backgroundColor: IsETT2OVl, borderBottomLeftRadius: 8, borderBottomRightRadius: 8, borderTopLeftRadius: 8, borderTopRightRadius: 8, boxShadow: "0px 4px 0px 0px rgb(201, 87, 87)", ...style }, ...addPropertyOverrides({ EVeBZmw_N: { "data-framer-name": "Variant 2" } }, baseVariant, gestureVariant), children: /* @__PURE__ */ _jsx(RichText, { __fromCanvasComponent: true, children: /* @__PURE__ */ _jsx(React.Fragment, { children: /* @__PURE__ */ _jsx(motion.p, { style: { "--font-selector": "RlM7QW50b24tcmVndWxhcg==", "--framer-font-family": '"Anton", "Anton Placeholder", sans-serif', "--framer-font-size": "24px", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-SrMRtag9J-PyNg7eZF4))" }, children: "ButtonText" }) }), className: "framer-1tyb8le", fonts: ["FS;Anton-regular"], layoutDependency, layoutId: "n6q1rRtaW", style: { "--extracted-r6o4lv": "var(--variable-reference-SrMRtag9J-PyNg7eZF4)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-SrMRtag9J-PyNg7eZF4": SrMRtag9J }, text: reO7G_gfv, verticalAlignment: "top", withExternalLayout: true }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-mWeqH.framer-1rood86, .framer-mWeqH .framer-1rood86 { display: block; }", ".framer-mWeqH.framer-fm9ith { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 8px 16px 8px 16px; position: relative; width: min-content; }", ".framer-mWeqH .framer-1tyb8le { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-mWeqH.framer-fm9ith { gap: 0px; } .framer-mWeqH.framer-fm9ith > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-mWeqH.framer-fm9ith > :first-child { margin-top: 0px; } .framer-mWeqH.framer-fm9ith > :last-child { margin-bottom: 0px; } }"];
var FramerPyNg7eZF4 = withCSS(Component, css, "framer-mWeqH");
var stdin_default = FramerPyNg7eZF4;
FramerPyNg7eZF4.displayName = "ModernButton";
FramerPyNg7eZF4.defaultProps = { height: 44.8, width: 133.25 };
addPropertyControls(FramerPyNg7eZF4, { variant: { options: ["dioJdgZpP", "EVeBZmw_N"], optionTitles: ["Variant 1", "Variant 2"], title: "Variant", type: ControlType.Enum }, IsETT2OVl: { defaultValue: "rgb(255, 90, 87)", title: "Background", type: ControlType.Color }, SrMRtag9J: { defaultValue: 'var(--token-805b626f-2081-48a3-9772-b35985201e4d, rgb(255, 250, 250)) /* {"name":"off-white"} */', title: "Color", type: ControlType.Color }, RN58auS3W: { title: "On Click", type: ControlType.EventHandler }, reO7G_gfv: { defaultValue: "ButtonText", displayTextArea: false, title: "Text", type: ControlType.String } });
addFonts(FramerPyNg7eZF4, [{ explicitInter: true, fonts: [{ family: "Anton", source: "fontshare", style: "normal", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TPY5PBRHOSXJ53WNSUYZQYX4FZUMAYNF/YHKM2QXXZHS7MS6DJUZXTGRXMIGWH7K5/PCXT6E5YCQO6SSVLT6UZPPGT7QKGXOUS.woff2", weight: "400" }] }], { supportsExplicitInterCodegen: true });

// virtual:modern-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "augiA20Il": { "path": "/" }, "iraOLFFrB": { "path": "/page" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "adefc19e7e2b72020fbf521cecd912ab5637e568e46b1420e141bd14e0cd2ee5",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "augiA20Il": {
          "path": "/"
        },
        "iraOLFFrB": {
          "path": "/page"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "adefc19e7e2b72020fbf521cecd912ab5637e568e46b1420e141bd14e0cd2ee5",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
