// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adefc19e7e2b7202 "S Clark - ArcAlert", do not edit manually */
"use client";

// virtual:paragraph-text
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/SNv5KTO1KzvxozUsWJt5/Gk1lDoqxxwF7FxAHXzhf/eqCELZoIK.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, RichText, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-8Hpx5";
var variantClassNames = { cQ_KypCao: "framer-v-16129sb" };
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var getProps = ({ color, height, id, text, width, ...props }) => {
  return { ...props, KbbIUFS2M: color ?? props.KbbIUFS2M ?? "var(--token-8a3dc925-cf3f-4305-931b-abd8bce0f792, rgb(255, 252, 252))", xQqPCMyZ3: text ?? props.xQqPCMyZ3 ?? "an emergency preparednessapp for today's world. " };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, KbbIUFS2M, xQqPCMyZ3, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "cQ_KypCao", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-16129sb", className, classNames), "data-framer-name": "Variant 1", layoutDependency, layoutId: "cQ_KypCao", ref: ref ?? ref1, style: { ...style }, children: /* @__PURE__ */ _jsx(RichText, { __fromCanvasComponent: true, children: /* @__PURE__ */ _jsx(React.Fragment, { children: /* @__PURE__ */ _jsx(motion.p, { style: { "--font-selector": "R2VvcmdpYQ==", "--framer-font-family": '"Georgia", sans-serif', "--framer-font-size": "23px", "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-KbbIUFS2M-eqCELZoIK))" }, children: "an emergency preparednessapp for today's world. " }) }), className: "framer-rjqqym", fonts: ["Georgia"], layoutDependency, layoutId: "pAG8Pb_fe", style: { "--extracted-r6o4lv": "var(--variable-reference-KbbIUFS2M-eqCELZoIK)", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline", "--variable-reference-KbbIUFS2M-eqCELZoIK": KbbIUFS2M }, text: xQqPCMyZ3, verticalAlignment: "top", withExternalLayout: true }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-8Hpx5.framer-b53fm6, .framer-8Hpx5 .framer-b53fm6 { display: block; }", ".framer-8Hpx5.framer-16129sb { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: wrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 300px; }", ".framer-8Hpx5 .framer-rjqqym { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 300px; word-break: break-word; word-wrap: break-word; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-8Hpx5.framer-16129sb { gap: 0px; } .framer-8Hpx5.framer-16129sb > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-8Hpx5.framer-16129sb > :first-child { margin-top: 0px; } .framer-8Hpx5.framer-16129sb > :last-child { margin-bottom: 0px; } }"];
var FramereqCELZoIK = withCSS(Component, css, "framer-8Hpx5");
var stdin_default = FramereqCELZoIK;
FramereqCELZoIK.displayName = "ParagraphText";
FramereqCELZoIK.defaultProps = { height: 82.8, width: 300 };
addPropertyControls(FramereqCELZoIK, { KbbIUFS2M: { defaultValue: "var(--token-8a3dc925-cf3f-4305-931b-abd8bce0f792, rgb(255, 252, 252))", title: "Color", type: ControlType.Color }, xQqPCMyZ3: { defaultValue: "an emergency preparednessapp for today's world. ", displayTextArea: false, title: "Text", type: ControlType.String } });
addFonts(FramereqCELZoIK, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:paragraph-text
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "augiA20Il": { "path": "/" }, "iraOLFFrB": { "path": "/page" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "adefc19e7e2b72020fbf521cecd912ab5637e568e46b1420e141bd14e0cd2ee5",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "augiA20Il": {
          "path": "/"
        },
        "iraOLFFrB": {
          "path": "/page"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "adefc19e7e2b72020fbf521cecd912ab5637e568e46b1420e141bd14e0cd2ee5",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
